# Generated by Django 5.1.4 on 2024-12-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('SCI', 'Science Fiction'), ('FAN', 'Fantasy'), ('MYS', 'Mystery'), ('THR', 'Thriller'), ('ROM', 'Romance'), ('HIS', 'Historical')], default='FIC', max_length=3),
        ),
    ]
